#!/usr/bin/env python3
"""
This module contains a function for asynchronous comprehension.

The async_comprehension function uses an
async generator to generate a list of floats.
"""

from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Generate a list of floats using an async generator.

    Returns:
        A list of floats generated by the async generator.
    """

    return [i async for i in async_generator()]
